#!/bin/bash
workingdir="$(pwd)"
gres_file=/usr/share/gnome-shell/gnome-shell-theme.gresource
gres_file_dir=$(dirname "$gres_file")
gres_xml=$(basename "$gres_file").xml


for res_dir in  `sudo gresource list $gres_file`; do
	res_dir="${res_dir#\/org\/gnome\/shell/}"
	if [ ! -d "$workingdir/${res_dir%/*}" ]; then
	  mkdir -p "$workingdir/${res_dir%/*}"
	fi
done
for res in `sudo gresource list $gres_file`;do
    sudo gresource extract $gres_file $res >$workingdir"/"${res#\/org\/gnome\/shell/}
    done
find . -name "*png" -type f -delete
find . -name "*jpg" -type f -delete
img_file_path="$(realpath "$1")"
img=$(basename $img_file_path)
change(){
    cp $img_file_path "$workingdir/theme/$img"
    old="#lockDialogGroup \{.*?\}"
    new="#lockDialogGroup {
	background: url('resource:\/\/\/org\/gnome\/shell\/theme\/$img');
	background-size: cover; }"
    perl -i -0777 -pe "s/$old/$new/s" "$workingdir"/theme/gdm3.css
}



create_xml(){
write(){
echo "<?xml version=1.0 encoding=UTF-8?>
<gresources>
  <gresource prefix='/org/gnome/shell/theme'>
	<file>$img</file>
        <file>calendar-today.svg</file>
        <file>checkbox-focused.svg</file>
        <file>checkbox-off-focused.svg</file>
        <file>checkbox-off.svg</file>
        <file>checkbox.svg</file>
        <file>dash-placeholder.svg</file>
        <file>gdm3.css</file>
        <file>gnome-shell-high-contrast.css</file>
        <file>gnome-shell.css</file>
        <file>icons/eye-not-looking-symbolic.svg</file>
        <file>icons/eye-open-negative-filled-symbolic.svg</file>
        <file>icons/keyboard-caps-lock-filled-symbolic.svg</file>
        <file>icons/keyboard-enter-symbolic.svg</file>
        <file>icons/keyboard-hide-symbolic.svg</file>
        <file>icons/keyboard-layout-filled-symbolic.svg</file>
        <file>icons/keyboard-shift-filled-symbolic.svg</file>
        <file>icons/message-indicator-symbolic.svg</file>
        <file>icons/pointer-double-click-symbolic.svg</file>
        <file>icons/pointer-drag-symbolic.svg</file>
        <file>icons/pointer-primary-click-symbolic.svg</file>
        <file>icons/pointer-secondary-click-symbolic.svg</file>
        <file>no-events.svg</file>
        <file>no-notifications.svg</file>
        <file>pad-osd.css</file>
        <file>process-working.svg</file>
        <file>toggle-off-dark.svg</file>
        <file>toggle-off-hc.svg</file>
        <file>toggle-off.svg</file>
        <file>toggle-on-dark.svg</file>
        <file>toggle-on-hc.svg</file>
        <file>toggle-on.svg</file>
    </gresource>
</gresources>"

}
write > $gres_xml
}

compile(){
    glib-compile-resources --sourcedir=./theme  ./gnome-shell-theme.gresource.xml
    sudo cp ./"$(basename "$gres_file")" "$gres_file_dir"
    sudo rm -rf theme $(basename "$gres_file") $gres_xml
    #sudo systemctl restart gdm3.service
    
}

change
create_xml
compile
